### ISSUE TITLE
Installation process is not clear

### ISSUE THREAD

**Issue by houmie** [OpenKitten/MongoKitten#115]
Sorry but why couldn't this be a pod?

I have been spending a couple of hours on https://medium.com/@joannis.orlandos/setting-up-mongokitten-4-9a8bf8b2ad09 and https://medium.com/@joannis.orlandos/using-spm-in-your-swift-projects-bf55996922a0. The steps aren't just clear.

I have created an empty folder, then ran `swift package init --type=executable` next I edited the Package.swift with the MongoKitten.

Then I compile it like this: `swift build -c release`. I have now an executable inside .builds/release.

And what do I do with it? How do I import it into my project? 

It is also unclear what I should put into `main.swift`. All I want to do is to connect via this lib to my mongo db. Can't I just treat this like a library? Very confusing...

Thanks,
Houman

**Comment by Obbut** [comment]
What platform are you developing for?

We primarily target server-side Swift (Linux and command line macOS applications) where the Swift Package Manager is the standard and the only option. So your project would be managed by the package manager. You can read more about the Swift Package manager [here](https://swift.org/package-manager/).

> Sorry but why couldn't this be a pod?

Because the entire server-side Swift world does not use Cocoapods. We don't work with Xcode projects and Cocoapods/Carthage like in standard iOS and macOS development. Distributing MongoKitten as a pod would introduce additional complexities in the project structure, and additional maintenance for a very small target audience (people writing database administration tools) that is not currently our core audience.

We also believe the Swift package manager will become the standard for iOS & macOS development over the next years, when it's more mature and integrated with Xcode. As such, we currently have no plans to introduce support for Cocoapods.

> And what do I do with it? How do I import it into my project?

With the Swift Package Manager, that's actually really easy. You would just add MongoKitten to your `Package.swift`, as we state in our readme, and then you can just `import MongoKitten` away. But again, we currently only really support projects that use the Swift Package Manager for dependency management.

Sadly, that does indeed mean that it does not really fit into conventional iOS / macOS applications that use Xcode projects and Cocoapods.

**Comment by Joannis** [comment]
I've got a solution for you, still, even though we don't support Cocoapods.

Create a directory inside your project named `SPM`. You can then create a project with `swift package init` (without `--type=executable`). That creates an SPM library. If you add your dependencies to this dummy-library you can create an Xcode project for the library using `swift package generate-xcodeproj`. This project can then be dragged into your `xcworkspace` for your project.

On your main project you'll need to edit the build phases of your xcodeproject for your application. You'll need to manually link the binary to all the libraries from SPM.

**Comment by acidmax76** [comment]
in this case build failed with errror on MongoSocket

**Comment by Joannis** [comment]
Can you provide more details @acidmax76 ?

**Comment by acidmax76** [comment]
i try compile like @Joannis wrote, create spm inside my project, then swift package init, then add in Packege.swift   dependencies  MongoKitten, then run swift package generate-xcodeproj , then add spm.xcodeproj in main workspace , then choose all MogoKitten library in build phases and when i try build main project  i got error "build  failed" on MongoSocket.framework

**Comment by Joannis** [comment]
@acidmax76 could you make a screenshot of the errors and/or post the entire error log?

**Comment by acidmax76** [comment]
sorry all work fine , i comment some stuf "...SSSlCert...." and build was complete

**Comment by Joannis** [comment]
Ah. You're running this on iOS? I don't intend to support iOS besides database browsers since it's a *really* bad practice security wise.

**Comment by acidmax76** [comment]
yes i run it on iOS

**Comment by Joannis** [comment]
For a Database Browser, or a normal application?

**Comment by acidmax76** [comment]
iam calling Server.getDatabases it's work . can i call any other method ?

**Comment by Joannis** [comment]
I've written a tonne of tutorials on medium. [This one about BSON](https://medium.com/@joannis.orlandos/the-bson-basics-1e70dd72e393) is essential, and [this one about queries](https://medium.com/@joannis.orlandos/the-mongokitten-query-object-8de2964d1b23), too. Once you get the hang of those, [CRUD operations](https://medium.com/@joannis.orlandos/crud-operations-in-mongokitten-4-5e7ced766160) is the next step.

When you get into more complex stuff, I've written *some* of it down in [this article about Advanced querying](https://medium.com/@joannis.orlandos/advanced-mongodb-querying-e7d4a50548ce) and [this one about aggregates](https://medium.com/@joannis.orlandos/using-mongodb-aggregates-from-mongokitten-d6337bbbadc8).

We also cover a lot in our [docs/tutorials](http://docs.openkitten.org) and the [generated docs for MongoKitten](http://mongokitten.openkitten.org).

If those aren't enough, you can always read in all detail about MongoDB [on the MongoDB website in their manual](https://docs.mongodb.com/manual/). We've got an article on [how to convert MongoDB tutorials to MongoKitten](https://medium.com/@joannis.orlandos/interpreting-official-mongodb-tutorials-and-applying-them-in-mongokitten-e34f62ba9969).

If the tutorials and docs aren't helping enough, create a separate issue here on github with the request for info. :)

**Comment by acidmax76** [comment]
tnx

**Comment by Obbut** [comment]
I think this is clear for now, so I'm closing the issue. If any of you still has a question feel free to open another one.
