### ISSUE TITLE
Locking database for crucial operations

### ISSUE THREAD

**Issue by sujaykakkad** [OpenKitten/MongoKitten#117]
Is there any way I can do read and write locks in mongo while doing multiple mongo queries to ensure data consistency.

**Comment by Joannis** [comment]
You an provide a ReadConcern and/or WriteConcern with your query depending on the operation.

You can apply them at collection and/or database-wide scale, too, by setting the `collection.readConcern`, `collection.writeConcern`, `database.readConcern` and `database.writeConcern` as necessary. Query provided concerns overwrite collection-wide,  which in turn overwrite database-wide.

More here: https://docs.mongodb.com/manual/reference/read-concern/
https://docs.mongodb.com/manual/reference/write-concern/

**Comment by sujaykakkad** [comment]
I guess readConcern and writeConcern is used for replica sets. How can it help to lock collection in single mongod instance.
eg.
I have 2 collections
customers
```js
[{_id: 1, name: "ABC"},{_id: 2, "name": "DEF"}]
```
orders
```js
[{_id: 1, customer_id: 1, amount: 200},{_id: 2, customer_id: 1, amount: 100},{_id: 3, customer_id: 2, amount: 150}]
```
now if a customer places order I will have an api
POST /orders
```js
{customer_id: 1, amount: 150}
```
The api will use 2 queries
1)Check if the customer exists in customers collection
2)Insert to orders collection

If in step 2 some parallel request deletes customer data then I will have data inconsistency
So I need to write lock customers collection till both the steps are complete.

How can I achieve this in mongo? Also tell me a way to use mongokitten to achieve this

**Comment by Joannis** [comment]
MongoDB usually has a writeahead log, so it'll tell you that the insert operation was completed but it's really in the writeahead log, not yet written to the collection.

WriteConcerns can modify this behaviour to only tell MongoKitten "insert operation was completed" *after* it was written to the collection, so when it's not in the writeahead anymore.

As for locking a collection against write operations, you can't. You'll need to take care of this in your application itself. Probably using `NSLock`. MongoKitten doesn't, can't want won't provide a way for you to lock collections since that's out of scope for a driver. 

We are building an Object Persistence Framework called [Meow](https://github.com/OpenKitten/Meow). Do you mind if I copy this issue to Meow as a feature request (regardless of whether you'll be using Meow or not). I think this is a *very* clear and good use case for me to work out.

**Comment by sujaykakkad** [comment]
Sure you can copy this issue.

**Comment by sujaykakkad** [comment]
But locking is such a crucial part in mongo as it doesn't provide transactions. How can I handle this example which I mentioned in mongo? Also I will have multiple api servers accessing same database so using I cannot use lock on application layer.

**Comment by sujaykakkad** [comment]
Also there is a documentation on concurrency
https://docs.mongodb.com/manual/faq/concurrency/

**Comment by sujaykakkad** [comment]
Or for such use cases I will have to use relational database

**Comment by Joannis** [comment]
For cross-application locks you *could* use Redis. In my tests redis was very simple and performant.
As for the documentation, it specifically states locks are not multi-document. So locks are for single read-write operations.

Alternatively, what I *can* find is this: https://docs.mongodb.com/manual/tutorial/perform-two-phase-commits/

I think this is something we could support in MongoKitten in the future. I'd like to see it implemented in the coming weeks, but I'm not sure if I'd be able to write and test that.

**Comment by sujaykakkad** [comment]
Two phase commit is very difficult to implement even in only two document transactions. In cases where there are more than two documents this method will be highly complicated. Is there any way mongo will release transactions in near future?

**Comment by Joannis** [comment]
I highly doubt it
