### ISSUE TITLE
Type 'DNSClient' has no member 'connectTS'

### ISSUE THREAD

**Issue by saroar** [OpenKitten/MongoKitten#227]
Here is error 

Type 'DNSClient' has no member 'connectTS' from MongoCluster file

<img width="1370" alt="Screenshot 2020-03-17 at 12 37 04 PM" src="https://user-images.githubusercontent.com/8770772/76843568-0bebe180-684d-11ea-9a17-5261b0f84974.png">

**Server-side Swift:**
 - OS: macOS
 - Swift Version: [e.g. 5.2]
 - MongoKitten  Version [e.g. 6.0.0]

**Additional context**

**Comment by Joannis** [comment]
Hey, sorry that I missed this issue. Were you using mobile/6.0 by any chance?

**Comment by freyaariel** [comment]
I’m experiencing the same issue on master/6.0 and I feel like I’ve tried everything to get it to compile but no dice. 😓

**Comment by Joannis** [comment]
@freyaariel what platform are you building for?

**Comment by freyaariel** [comment]
@Joannis this is when building for iOS (inside a Swift package, not Xcode project, if that matters).

It’s weird because I can clearly see that the `connectTS()` method exists in `DNSClient`.

Building for macOS works fine; watchOS and tvOS too (after adding these platforms to Package.swift), so it seems like an issue with NIO Transport Services or somehow with the `#if canImport(NIOTransportServices) && os(iOS)` conditionals.

**Comment by Joannis** [comment]
@freyaariel MongoKitten doesn't support iOS on this branch, even though there's an `#if os(iOS)` condition. The branch where I maintain iOS support is `mobile/6.0`, and unless you really know what you're doing I highly suggest not using MongoKitten on an iOS device. In order to connect to MongoDB (or any other database) you'll need to embed the credentials in the binary. At that point hacking your application is trivial.

**Comment by freyaariel** [comment]
Thank you for the quick reply and thanks pointing me in the right direction, @Joannis, and I appreciate the security disclaimer also. I’m trying to make an app that can display results of arbitrary queries in widgets. Users input their own server info so no credentials are embedded in this case.

It compiles successfully for iOS using `mobile/6.0`. ✅🎉

**Comment by Joannis** [comment]
Looks like you're building a competitor to my app :) Good luck!
