### ISSUE TITLE
Question regarding arrays

### ISSUE THREAD

**Issue by justmark** [OpenKitten/MongoKitten#27]
Hi,

Great work on this project - my  team has been playing with MongoKitten a fair amount of late, and have run into an issue that I'm hoping you can answer for us.  Our version of Swift is:
3.0-PREVIEW-2 on Ubuntu 15.10.

I created a simple document for this test in Mongo.  It is:

```
{
   "_id": ObjectId("57989a7e76ac858d418faf42"),
   "name": "Test",
   "vals": [ 1,2,3,4,5 ] 
}
```

If we print out the vals array, we end up with:
array(BSON.Document(storage: [60, 0, 0, 0, 1, 48, 0, 0, 0, 0, 0, 0, 0, 240, 63, 1, 49, 0, 0, 0, 0, 0, 0, 0, 0, 64, 1, 50, 0, 0, 0, 0, 0, 0, 0, 8, 64, 1, 51, 0, 0, 0, 0, 0, 0, 0, 16, 64, 1, 52, 0, 0, 0, 0, 0, 0, 0, 20, 64, 0], _count: nil))

This wasn't what we were expecting.  We've tried to specify that the results were an Array, but this tosses an error.  If we try and iterate over "vals" we end up with another error:

error: type 'Value' does not conform to protocol 'Sequence'

If we use doc["vals"][0] we end up with:
double(1.0)

Attempting to get .count on "vals" generates another error:

error: value of type 'Value' has no member 'count'

We're coming from the Ruby/Mongoid world.  We're clearly missing something regarding Array processing with MongoKitten.

Thoughts?

**Comment by Obbut** [comment]
I'm going to look into this either this evening (right now its 18:00 here) or tomorrow!

**Comment by justmark** [comment]
Thanks - looking forward to hearing from you!

**Comment by justmark** [comment]
Hi,

I was using version 1.1.  Just switched to v1.2 and I'm getting an Array response now, and things are working as expected.  Hopefully I didn't waste any of your time.

Thanks!

**Comment by Obbut** [comment]
[Our BSON library](https://github.com/openkitten/bson) always returns an enum (`Value`) when subscripting a document. `Value` contains the following enum cases:

```
    case double(Double)
    case string(String)
    case document(Document)
    case array(Document)
    case binary(subtype: BinarySubtype, data: [UInt8])
    case objectId(ObjectId)
    case boolean(Bool)
    case dateTime(Date)
    case null
    case regularExpression(pattern: String, options: String)
    case javascriptCode(String)
    case javascriptCodeWithScope(code: String, scope: Document)
    case int32(Int32)
    case timestamp(stamp: Int32, increment: Int32)
    case int64(Int64)
    case minKey
    case maxKey
    case nothing
```

A BSON array is really just a document with keys from 0 to x, so the enum case for `array` has a document as it's associated value. Because `Value` can also be, say, a double or a date, it doesn't conform to the `Sequence` protocol.

The easiest way to iterate over the array is by using the `document` convenience accessor on `Value`. This returns the underlying document if `Value` is either an array or document, or an empty document if it's something else. You can then iterate like this:

```swift
for (key, val) in doc["vals"].document {
    print("Value is \(val)")
}
```

That will produce the following output:
```
Value is double(1.0)
Value is double(2.0)
Value is double(3.0)
Value is double(4.0)
Value is double(5.0)
```

You can also use `documentValue` instead of `document`. `documentValue` will return `nil` instead of an empty document when the underlying value isn't a document.

These accessors exist for other types, too. For an overview, you can have a look at [this file](https://github.com/OpenKitten/BSON/blob/master/Sources/Value%2BExtraction.swift), where they are defined.


Does this solve the issue you are having?

**Comment by justmark** [comment]
That did the trick.  Thanks.

And thanks for the detailed answer.  Very much appreciated.

**Comment by Obbut** [comment]
No problem, feel free to open another issue if you have any other questions!

**Comment by duncangroenewald** [comment]
Hi, I am trying to do something similar but this solution is not working for me.  

My document looks like this:

{"updated":{"$date":"2016-01-16T17:58:45.171+11:00"},
 "name":"XXXX",
 "status":true,
 "_id":{"$oid":"57297a76b30bbf896e0a1c55"},

 "groups":[
	{"name":"Configuration Testing", 
	 "allow_auto_approval":false, 
	 "_id":{"$oid":"5699ea252529119457a40a67"}, 
	 "expected_users":30, 
	 "code":"632DZ0"
	},
	{"name":"Solution Demonstration", 
	 "allow_auto_approval":false, 
	 "_id":{"$oid":"5699ea252529119457a40a68"}, 
	 "expected_users":50, 
	 "code":"632GN1"}
 ]
 }

and I want to iterate over the groups array so I would expect the following to work:

for (key, val) in doc["groups"].document {
   print("Value is \(val)")
}

but this failed with a syntax error.

**Comment by Joannis** [comment]
@duncangroenewald this is older MongoKitten syntax. Nowadays we're extracting using initializers.

http://beta.openkitten.org/bson/BSON/

**Comment by duncangroenewald** [comment]
Can you provide an example of how to extract a subdocument from data returned from MongoDB - sorry I couldn't find any explanation of how to do this at the link above.

**Comment by Joannis** [comment]
```swift
for (key, val) in Document(doc["groups"]) ?? [] {
  print("Value is \(val)")
}
```

I want to expand this API for MongoKitten 5 to contain:

```swift
for (key, val) in try Document(assert: doc["groups"]) {
  print("Value is \(val)")
}
```

and

```swift
for (key, val) in Document(defaultToEmpty: doc["groups"]) {
  print("Value is \(val)")
}
```

**Comment by duncangroenewald** [comment]
Cool - thanks for that.
