### ISSUE TITLE
initting the Server with config file?

### ISSUE THREAD

**Issue by maxydon** [OpenKitten/MongoKitten#46]
Hello I was wondering how can I init a Server object automatically with the ./Config/secrets/mongo.json information?

**Comment by Joannis** [comment]
I think this is an issue with VaporMongo rather than MongoKitten. We don't use configuration files at all. VaporMongo has a [file](https://github.com/vapor/mongo-provider/blob/master/Sources/VaporMongo/Provider.swift) that initializes an object using a configuration file.

It's JSON seems to look like this:

```json
{
  "mongo": {
    "database": "myDatabaseName",
    "user": "myUsername",
    "password": "myPassword",
    "host": "localhost",
    "port": 27017
  }
}
```

The host and port seem optional and default to `localhost:27017`.
That's as far as I can go in assisting you since I'm not a maintainer of VaporMongo. For that you'll need to ask around in the vapor community and/or it's primary module maintainers.

**Comment by maxydon** [comment]
I'm not sure Iunderstand the asnwer: with vapor mongo I can i could create the mongo.json file and initialize the db with `Droplet(providers: [VaporMongo.Provider.self])` but since I'm using mongoKitten instead, i have to create the server with all the information in the app.swift (if i'm not missing something).

**Comment by Joannis** [comment]
If you're using MongoKitten directly you'll need to parse the configuration file manually (or using Vapor) and pass the config file information to `MongoKitten.Server` yourself. We don't support config formats like Vapor's by default. But I'm sure that if you're using Vapor you can create or get a `Config` object. Then you'll need to extract the information from the config object like Vapor does [here](https://github.com/vapor/mongo-provider/blob/master/Sources/VaporMongo/Provider.swift) and pass it to the Server object.
