### ISSUE TITLE
MongoKitten failing with "Context is nil" error

### ISSUE THREAD

**Issue by vincent-coetzee** [OpenKitten/MongoKitten#68]
Hi there
I'm trying to access a Compose MongoDB database with a connection URL of the following form

**mongodb://user:password@host:port/admin?ssl=true**

I have built my MongoKitten with MongoTLS defined, and I have checked that MongoKitten is in fact using TLS, and it is. Creating the Server instance works without failing, but when I attempt to insert into a collection, MongoKitten fails with the following error

**The MongoKitten background loop encountered an error and has stopped: receive("Context is nil")
Please file a report on https://github.com/openkitten/mongokitten
send("Context is nil")**

If I take the parameters from the URL and execute

**mongo --ssl --sslAllowInvalidCertificates host:port/admin -u user -p password**

mongo works correctly and allows me to access the database. Am I doing something incorrect or is this a bug in MongoKitten. Can you suggest a solution or let me know if this is in fact a bug. 

Thanks

**Comment by Joannis** [comment]
This is related to #16. Support is not yet complete and tested. Support is experimental at best. I've been trying to get it up and running myself but I'm unable to connect using SSL myself, too.

MongoKitten is able to select a database since in MongoKitten 2 this doesn't open a connection yet. The connection pool doesn't need a connection to interact with the database until you insert the data. At that point it's creating it's first connection in the pool and attempts to authenticate which is when SSL doesn't correctly connect.

I'll continue to work on SSL, but I can't give you a proper ETA on when I'll have it working.

**Comment by vincent-coetzee** [comment]
Hi Joannis,

Thanks for the prompt response and thanks for letting me know. That’s a real pity, as I was really hoping to use MongoKitten for an upcoming commercial project.

But many thanks anyway.

Regards

**Comment by Joannis** [comment]
@vincent-coetzee MongoKitten 3 is planned for release Friday 16 december. It'll support replica sets for sure and SSL is definitely planned to be working and tested by then. I'm unsure if I'll meet SSL support by then but I'll report in this thread if I make any progress. If anyone reading this is able to help me implement SSL support using Vapor/TLS then please do respond!

**Comment by lgaches** [comment]
@Joannis I'm working on SSL support. I've a successful connection to a local mongoDB 3.4. Just let me clean my code before a Pull request. I'll try to do it before the end of the week.

**Comment by Joannis** [comment]
Amazing! Thanks so much for that! Could you push the code to a GitHub repository? I'd love to have a look at how you pulled it off!
