### ISSUE TITLE
Matching subdocuments/nested objects

### ISSUE THREAD

**Issue by wpccolorblind** [OpenKitten/MongoKitten#69]
Hey all,

Trying to figure out how to do the equivalent of this with MongoKitten:

Sample object:

{
     name: "Bob",
     nestedThings : {
          "thing1": [0, 1, 2],
          "thing2": [2, 3, 4]
     }
}

db.getCollection('myCollection').find({"nestedThings.thing1" : {$exists: true}})

This works perfectly fine as a regular mongo query, but haven't figured out if this is possible in MongoKitten.

Tried:

let matchingDoc = Document()
matchingDoc["nestedThings.thing1"] = [
            "$exists" : true
        ]

The above works for:

matchingDoc["nestedThings"] = [
            "$exists" : true
        ]

Thanks!

**Comment by Joannis** [comment]
I know the problem here 😬
MongoKitten 2 (the one you're likely running) still had the stupid feature called 'dot-notation'. I think you'll find this working with variadic subscripts.

```swift
let matchingDoc = Document()
matchingDoc["nestedThings", "thing1"] = [
"$exists" : true
]
```

**Comment by Joannis** [comment]
Oops. I've made a mistake in my example "working" code. The code I showed you does the exact same thing you did.

```swift
let matchingDoc = Document()
matchingDoc[["nestedThings"]] = [
"$exists" : true
]
```

That should disable the dot notation triggering.

**Comment by wpccolorblind** [comment]
Your reponses are a little confusing to me...

I'm using MongoKitten 3 / Swift 3.

My goal is to select only documents that have a nestedThings object that also have a thing1 subobject.

I've tried:

1- 
let matchingDoc = Document()
matchingDoc["nestedThings", "thing1"] = [
"$exists" : true
]

--> returns 0 documents

2-
let matchingDoc = Document()
matchingDoc[["nestedThings"]] = [
"$exists" : true
]

--> returns all documents that have a nestedThings object, but that is not the goal.

**Comment by Joannis** [comment]
First let's get the terms down so get the confusion out of the way.
MongoKitten is this library which officially is still at version 2. Version 3 is in development and is accessible using a tag instead of a version number.

MongoKitten 2 (the one I think you're running) has a feature called dot notation which is triggered when you enter precisely 1 string into the subscript.

`matchingDoc["oneString"]`

If you have embedded Documents you can access them easily using dot notation or variadic subscripts.

Dot notation: `matchingDoc["dot.notated.string"]`
Variadic: `matchingDoc["dot", "notated", "string]`

However, this doesn't solve your problem since you want MongoKitten to create a key that has dots in the key like "nestedThings.thing1".

So for that you'll need to use a workaround, sadly, until MongoKitten 3 releases. I'd suggest this approach:

`matchingDoc[["nestedThings.thing1"]]`. This will trigger the variadic subscript which does not separate dot notation, but with a dot notated key.

**Comment by wpccolorblind** [comment]
Gotcha regarding v2 vs. v3.

matchingDoc[["nestedThings.thing1"]] is still not working though.  Tried variadic just for kicks and that didn't work either.

**Comment by Joannis** [comment]
Apparently there was a bug inside that subscript (`matchingDoc[["nestedThings.thing1]]`). @Obbut fixed it 🎉
