### ISSUE TITLE
"Ambiguous use of subcript" when trying to access document value

### ISSUE THREAD

**Issue by ntokozotep** [OpenKitten/MongoKitten#81]
Hi,

According to https://github.com/OpenKitten/Documentation/blob/master/BSON/Tutorials/Document.md, documents are usable like dictionaries. However, when trying to access a value using a key, this error is given: ```Ambiguous use of subscript```.

I have been following this Vapor with MongoKitten tutorial: https://medium.com/@xcadaverx/full-stack-swift-deploying-a-vapor-app-4a190bc0a8d#.ld2gy0vnj. In it, the author is able to access document values in the following way:
```
guard let uniqueID = document["unique_id"].stringValue else {
    return nil
}
```
That was with MongoKitten version 1.1. Now the above code gives the error: ```Ambiguous reference to member 'subscript(dotNotated:)'```

Please assist.

**Comment by Joannis** [comment]
MongoKitten 3's BSON Document supports 3 kinds of subscripts. The one you're looking for is `document["unique_id"] as String?`. BSON now requires you to explicitely define the type you want to have extracted there.

**Comment by ntokozotep** [comment]
Okay. Thanks Joannis

**Comment by zirinisp** [comment]
@Joannis I cannot understand the new syntax. Why use "as String?" and not "as? String" or stringValue. Can you please point me to a direction that I can have a better understanding

**Comment by Joannis** [comment]
We now have 20 almost identical subscripts. The only difference between each subscript is the return value. So if you're looking for a String you'll need the subscript that returns the String... however, Swift usually infers types rather than having you explicitly define them causing the subscript to be ambiguous. This is why you a subscript like this: `document["subdoc", "subdoc", "key"]` will be ambiguous for extraction. And will need to have it's type defined.

`as String?` is an explicit definition to the compiler that you're looking for a `String?` return type.
`as? String` would mean you're casting a protocol type to a String type, and `nil` if it's not a String.
`.stringValue` is still possible but you'd need the raw value. And however I did want it to work that way it's currently impossible to disambiguate a function/subscript without an explicit pointer. If I'd have the ability to do so, I'd have tried to make raw subscripts the default without messing up the signature for other types.

If you want to use `as? String` you currently need to specify the subscript as raw.
`document[raw: "path", "to", "key"]`

Does this clarify it for you?

**Comment by Joannis** [comment]
Just a little open question to everyone reading this:
If you would've written the BSON library behind MongoKitten. How would you set up the subscripting?
