### ISSUE TITLE
The sortedBy in find() does not work properly

### ISSUE THREAD

**Issue by xiongyuxi** [OpenKitten/MongoKitten#95]
Hi, the sortedBy in find() not work properly for me, I use mongoDB 2.6.10 with MongoKitten:
Package(url: "https://github.com/OpenKitten/MongoKitten.git", majorVersion: 3)

```
let findDocument: Document = [
            "ID": ID
        ]
        
let findDocumentQuery = Query(findDocument)
        
let sortByTime: Sort = [
            "time": .descending
        ]
        
let myCursor = try database[aswString].find(matching:findDocumentQuery,sortedBy:sortByTime)
```

The Cursor will ignore the sortedBy parameter and always return the top row of collection/table.

**Comment by xiongyuxi** [comment]
try running same code with MongoDB 3.4, the sortedBy works in MongoDB 3.4, but not work with 2.6.

**Comment by Joannis** [comment]
MongoDB 2.6 doesn't seem to allow you to sort queried information, so unless I implement sorting in MongoKitten itself it won't work for MongoDB 2.6. I have no plans to implement advanced support for all MongoDB features for MongoDB 2.6 since that's an impossible that would have me end up rewriting almost all of MongoDB in the driver, that's not an option.

**Comment by xiongyuxi** [comment]
Thanks for your reply. I didn't know that. I just use .find().sort({"abc":-1}) in MongoDB2.6 and it seems works fine. I have update the DB to 3.2 now. Thanks again for your reply.
