### ISSUE TITLE
Socket multi-threading crash

### ISSUE THREAD

**Issue by tfrank64** [OpenKitten/MongoKitten#98]
When running performance tests, with Jmeter, that use greater than 1 thread, my application crashes in MongoKitten. [This line](https://github.com/lgaches/MongoKitten/blob/mk31-BlueSSL/Sources/MongoKitten/Socket/Connection.swift#L119) or sometimes [this line](https://github.com/lgaches/MongoKitten/blob/mk31-BlueSSL/Sources/MongoKitten/Socket/Connection.swift#L109) specifically.
The error I get is:

    fatal error: Array replace: subrange extends past the end

My performance tests involve 100k+ queries against my server and mongoDB. I found that when running these tests on one thread, it works great, but anything more causes the crash mentioned above.

**Comment by rfdickerson** [comment]
The error happens when the buffer's length is 0. As expected, indexing into this zero-length buffer causes a run-time exception. It seems that the buffer seems to be cleared when another thread is busy in the read. We tried placing simple locks around this critical section, but the fact that this area included a recursive call to itself, makes locking it difficult.

**Comment by rfdickerson** [comment]
I think we might be able to close this out with MongoKitten 4

**Comment by Joannis** [comment]
I'll be trying to backport this. But it works 🎉
